name: flutter_analysis_options
description: A custom analysis_options.yaml file based on effective_dart.
version: 0.1.0
publish_to: 'none'
homepage: https://github.com/defuncart/flutter_analysis_options
repository: https://github.com/defuncart/flutter_analysis_options
issue_tracker: https://github.com/defuncart/flutter_analysis_options/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  effective_dart: ^1.2.0
